import Link from "next/link";
import { ArrowRight, Upload, Download, Zap, CheckCircle } from "lucide-react";
import { notFound } from "next/navigation";

const PLATFORMS: Record<string, {
  name: string;
  fullName: string;
  description: string;
  color: string;
  gradient: string;
  cropPixels: number;
  features: string[];
  seoTitle: string;
  seoDescription: string;
}> = {
  sora: {
    name: "Sora",
    fullName: "OpenAI Sora",
    description: "Remove the Sora watermark from OpenAI's text-to-video AI generated content. Clean videos ready for professional use.",
    color: "purple",
    gradient: "from-purple-500 to-pink-500",
    cropPixels: 100,
    features: [
      "Removes bottom watermark automatically",
      "Preserves original 1080p quality",
      "Keeps audio track intact",
      "Fast 5-15 second processing",
    ],
    seoTitle: "Remove Sora Watermark - Free AI Video Watermark Remover",
    seoDescription: "Instantly remove OpenAI Sora watermarks from your AI-generated videos. Fast, free, and high-quality watermark removal.",
  },
  tiktok: {
    name: "TikTok",
    fullName: "TikTok",
    description: "Remove TikTok watermarks and logos from downloaded videos. Perfect for repurposing content across platforms.",
    color: "cyan",
    gradient: "from-cyan-500 to-blue-500",
    cropPixels: 80,
    features: [
      "Removes TikTok logo and username",
      "Works with any TikTok video",
      "No quality loss",
      "Batch processing available",
    ],
    seoTitle: "Remove TikTok Watermark - Free Video Watermark Remover",
    seoDescription: "Remove TikTok watermarks from videos instantly. Download clean videos without the TikTok logo for any platform.",
  },
  runway: {
    name: "Runway",
    fullName: "Runway Gen-2",
    description: "Clean up Runway Gen-2 AI videos by removing the watermark. Professional-grade output for your creative projects.",
    color: "green",
    gradient: "from-green-500 to-emerald-500",
    cropPixels: 60,
    features: [
      "Optimized for Runway Gen-2 output",
      "Maintains video resolution",
      "Audio preserved perfectly",
      "Works with all Runway exports",
    ],
    seoTitle: "Remove Runway Watermark - Gen-2 AI Video Cleaner",
    seoDescription: "Remove Runway Gen-2 watermarks from AI-generated videos. Get clean, professional video output instantly.",
  },
  pika: {
    name: "Pika",
    fullName: "Pika Labs",
    description: "Remove Pika Labs watermarks from your AI-generated videos. Get clean exports for your creative work.",
    color: "orange",
    gradient: "from-orange-500 to-red-500",
    cropPixels: 50,
    features: [
      "Designed for Pika output format",
      "Smart watermark detection",
      "Lossless video processing",
      "Quick turnaround time",
    ],
    seoTitle: "Remove Pika Watermark - Pika Labs Video Cleaner",
    seoDescription: "Instantly remove Pika Labs watermarks from AI videos. Clean, professional results in seconds.",
  },
  kling: {
    name: "Kling",
    fullName: "Kuaishou Kling AI",
    description: "Remove Kling AI watermarks from videos generated by Kuaishou's text-to-video model.",
    color: "blue",
    gradient: "from-blue-500 to-indigo-500",
    cropPixels: 70,
    features: [
      "Works with Kling AI exports",
      "Removes Chinese watermarks",
      "Full HD quality preserved",
      "Fast cloud processing",
    ],
    seoTitle: "Remove Kling Watermark - Kuaishou AI Video Cleaner",
    seoDescription: "Remove Kling AI watermarks from your videos. Fast, easy watermark removal for Kuaishou generated content.",
  },
  luma: {
    name: "Luma",
    fullName: "Luma Dream Machine",
    description: "Clean up Luma Dream Machine videos by removing the watermark overlay. Perfect for professional content.",
    color: "yellow",
    gradient: "from-yellow-500 to-orange-500",
    cropPixels: 55,
    features: [
      "Optimized for Dream Machine output",
      "Preserves video smoothness",
      "No re-encoding artifacts",
      "Works with all resolutions",
    ],
    seoTitle: "Remove Luma Watermark - Dream Machine Video Cleaner",
    seoDescription: "Remove Luma Dream Machine watermarks instantly. Get clean AI videos ready for any platform.",
  },
};

export async function generateMetadata({ params }: { params: { platform: string } }) {
  const platform = PLATFORMS[params.platform];
  if (!platform) return { title: "Platform Not Found" };
  
  return {
    title: platform.seoTitle,
    description: platform.seoDescription,
  };
}

export default function PlatformPage({ params }: { params: { platform: string } }) {
  const platform = PLATFORMS[params.platform];
  
  if (!platform) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-gradient-to-b from-gray-900 via-gray-900 to-black text-white">
      {/* Header */}
      <header className="container mx-auto px-6 py-6 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
            <span className="text-xl font-bold">B</span>
          </div>
          <span className="text-xl font-bold">BlankLogo</span>
        </Link>
        <nav className="flex items-center gap-6">
          <Link href="/pricing" className="text-gray-300 hover:text-white transition">
            Pricing
          </Link>
          <Link
            href="/login"
            className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 transition font-medium"
          >
            Get Started
          </Link>
        </nav>
      </header>

      {/* Hero */}
      <section className="container mx-auto px-6 py-16 text-center">
        <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r ${platform.gradient} text-white text-sm mb-6`}>
          <Zap className="w-4 h-4" />
          <span>{platform.fullName} Watermark Remover</span>
        </div>
        
        <h1 className="text-4xl md:text-6xl font-bold mb-6">
          Remove {platform.name} Watermarks<br />
          <span className={`bg-gradient-to-r ${platform.gradient} bg-clip-text text-transparent`}>
            Instantly
          </span>
        </h1>
        
        <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-10">
          {platform.description}
        </p>
        
        <Link
          href="/app"
          className={`inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-gradient-to-r ${platform.gradient} text-white font-semibold text-lg hover:opacity-90 transition`}
        >
          Remove {platform.name} Watermark <ArrowRight className="w-5 h-5" />
        </Link>
      </section>

      {/* Features */}
      <section className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-6">
          {platform.features.map((feature, i) => (
            <div key={i} className="flex items-start gap-3 p-4 rounded-xl bg-white/5 border border-white/10">
              <CheckCircle className={`w-6 h-6 text-${platform.color}-400 flex-shrink-0 mt-0.5`} />
              <span className="text-gray-300">{feature}</span>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works */}
      <section className="container mx-auto px-6 py-16 border-t border-white/10">
        <h2 className="text-3xl font-bold text-center mb-12">
          How to Remove {platform.name} Watermarks
        </h2>
        
        <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
          <div className="text-center p-6">
            <div className={`w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-r ${platform.gradient} flex items-center justify-center`}>
              <Upload className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-2">1. Upload Video</h3>
            <p className="text-gray-400">
              Upload your {platform.name} video or paste a URL
            </p>
          </div>
          
          <div className="text-center p-6">
            <div className={`w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-r ${platform.gradient} flex items-center justify-center`}>
              <Zap className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-2">2. Auto-Process</h3>
            <p className="text-gray-400">
              We detect and remove the watermark automatically ({platform.cropPixels}px crop)
            </p>
          </div>
          
          <div className="text-center p-6">
            <div className={`w-16 h-16 mx-auto mb-4 rounded-2xl bg-gradient-to-r ${platform.gradient} flex items-center justify-center`}>
              <Download className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-xl font-semibold mb-2">3. Download</h3>
            <p className="text-gray-400">
              Get your clean video in seconds
            </p>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="container mx-auto px-6 py-16">
        <div className={`max-w-4xl mx-auto p-12 rounded-3xl bg-gradient-to-r ${platform.gradient} text-center`}>
          <h2 className="text-3xl font-bold mb-4">
            Ready to Clean Your {platform.name} Videos?
          </h2>
          <p className="text-xl text-white/80 mb-8">
            Start with 5 free credits. No credit card required.
          </p>
          <Link
            href="/app"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-white text-gray-900 font-semibold text-lg hover:bg-gray-100 transition"
          >
            Remove Watermark Free <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Other Platforms */}
      <section className="container mx-auto px-6 py-16 border-t border-white/10">
        <h2 className="text-2xl font-bold text-center mb-8">
          Also Remove Watermarks From
        </h2>
        <div className="flex flex-wrap justify-center gap-3">
          {Object.entries(PLATFORMS)
            .filter(([key]) => key !== params.platform)
            .map(([key, p]) => (
              <Link
                key={key}
                href={`/remove/${key}`}
                className={`px-4 py-2 rounded-full bg-gradient-to-r ${p.gradient} text-white text-sm font-medium hover:opacity-90 transition`}
              >
                {p.name}
              </Link>
            ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-6 py-8 border-t border-white/10 text-center text-gray-500">
        <p>&copy; {new Date().getFullYear()} BlankLogo. All rights reserved.</p>
      </footer>
    </main>
  );
}
