"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 via-gray-900 to-black text-white">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-gray-400 hover:text-white mb-8 transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-gray-400 mb-8">
          Effective Date: January 11, 2026 | Last Updated: January 11, 2026
        </p>

        <div className="prose prose-invert prose-lg max-w-none space-y-8">
          <p className="lead text-xl text-gray-300">
            BlankLogo (&quot;BlankLogo,&quot; &quot;we,&quot; &quot;us,&quot; &quot;our&quot;) is operated by Dupree Ops LLC (&quot;Company&quot;). This Privacy Policy explains how we collect, use, disclose, and protect information when you visit blanklogo.app or use our video watermark removal services (the &quot;Service&quot;).
          </p>
          <p className="text-gray-400">
            If you do not agree with this Privacy Policy, do not use the Service.
          </p>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">1) Who We Are</h2>
            <div className="bg-gray-800/50 rounded-lg p-6">
              <p className="text-white font-semibold text-lg mb-2">Dupree Ops LLC</p>
              <p className="text-gray-300">
                3425 Delaney Drive, Florida, United States<br /><br />
                <strong>Privacy:</strong> <a href="mailto:privacy@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">privacy@blanklogo.app</a><br />
                <strong>Support:</strong> <a href="mailto:support@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">support@blanklogo.app</a>
              </p>
            </div>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">2) Information We Collect</h2>
            
            <h3 className="text-xl font-semibold mt-6 mb-3">A) Information you provide</h3>
            <p className="text-gray-300 mb-2">We collect information you provide directly to us, including:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li><strong>Account information:</strong> email address and basic account identifiers.</li>
              <li><strong>Support communications:</strong> messages you send to us and any information included.</li>
              <li><strong>Purchase/plan details:</strong> plan selection, credits purchased, subscription status, and transaction history.</li>
            </ul>
            <p className="text-gray-400 text-sm mt-3">Payments are processed by third-party payment processors. We do not store full payment card details on our servers.</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">B) Content you upload / submit for processing</h3>
            <p className="text-gray-300 mb-2">We collect and process:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Uploaded videos and/or URLs you provide for watermark removal.</li>
              <li>Processed outputs generated by the Service.</li>
              <li>Job metadata: file type, file size, timestamps, processing mode used, job status (queued/processing/completed/failed), and technical logs needed to run and troubleshoot the Service.</li>
            </ul>
            <div className="bg-yellow-900/20 border border-yellow-600/30 rounded-lg p-4 mt-4">
              <p className="text-yellow-200 text-sm">
                <strong>Note:</strong> Your videos may include personal information (e.g., faces, voices, personal identifiers). Only upload content you have the right to use and process.
              </p>
            </div>

            <h3 className="text-xl font-semibold mt-6 mb-3">C) Information collected automatically</h3>
            <p className="text-gray-300 mb-2">When you use the Service, we may automatically collect:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li><strong>Device and usage data:</strong> IP address, device type, browser type, operating system, referring URLs, pages viewed, and interaction events.</li>
              <li><strong>Cookies and similar technologies:</strong> used for authentication, security, and analytics/measurement (see Section 7).</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3">D) Analytics and advertising / retargeting</h3>
            <p className="text-gray-300 mb-2">We use analytics and retargeting to understand performance and improve marketing efficiency. This can include:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Event data such as page views, signups, logins, checkout starts, purchases, and other interactions.</li>
              <li>Advertising measurement and retargeting cookies/pixels (e.g., Meta Pixel) to show relevant ads to users who have visited our site or interacted with our content.</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">3) How We Use Information</h2>
            <p className="text-gray-300 mb-4">We use your information to:</p>

            <h3 className="text-lg font-semibold mt-4 mb-2">1. Provide and operate the Service</h3>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Create and manage accounts</li>
              <li>Process video jobs and deliver outputs</li>
              <li>Manage credits, subscriptions, and billing status</li>
              <li>Provide download links and notifications</li>
            </ul>

            <h3 className="text-lg font-semibold mt-4 mb-2">2. Improve reliability, performance, and product quality</h3>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Diagnose processing failures</li>
              <li>Monitor performance and prevent silent failures</li>
              <li>Improve user experience and workflows</li>
            </ul>

            <h3 className="text-lg font-semibold mt-4 mb-2">3. Communicate with you</h3>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Transactional emails (receipts, account notices, processing notifications)</li>
              <li>Support responses and service updates</li>
            </ul>

            <h3 className="text-lg font-semibold mt-4 mb-2">4. Security and fraud prevention</h3>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Prevent abuse (e.g., automated scraping, malicious uploads, fraudulent signups)</li>
              <li>Protect users and platform integrity</li>
            </ul>

            <h3 className="text-lg font-semibold mt-4 mb-2">5. Analytics and marketing</h3>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Understand what drives conversions and retention</li>
              <li>Run retargeting ads and measure their effectiveness (see Section 7)</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">4) Legal Bases for Processing (GDPR/UK GDPR)</h2>
            <p className="text-gray-300 mb-3">If you are located in the EU/UK, we process personal data under the following legal bases:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li><strong>Contract:</strong> to provide the Service (processing your videos, managing credits/subscriptions).</li>
              <li><strong>Legitimate Interests:</strong> securing the Service, improving performance, analytics, and fraud prevention.</li>
              <li><strong>Consent:</strong> where required for certain cookies/retargeting technologies.</li>
              <li><strong>Legal Obligation:</strong> compliance with applicable laws and lawful requests.</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">5) How We Share Information</h2>
            <div className="bg-green-900/20 border border-green-600/30 rounded-lg p-4 mb-4">
              <p className="text-green-200 font-semibold">We do not sell your personal information.</p>
            </div>
            <p className="text-gray-300 mb-4">We may share information with:</p>

            <h3 className="text-xl font-semibold mt-4 mb-3">A) Service providers (subprocessors)</h3>
            <p className="text-gray-300 mb-2">We use third-party providers to operate the Service, such as:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Hosting, storage, and compute infrastructure</li>
              <li>Authentication and database services</li>
              <li>Payment processors</li>
              <li>Email delivery providers</li>
              <li>Analytics and error monitoring services</li>
              <li>Advertising/measurement partners for retargeting (e.g., Meta)</li>
            </ul>
            <p className="text-gray-400 text-sm mt-2">These vendors are authorized to process information only to perform services for us and are typically bound by confidentiality and data protection obligations.</p>
            <p className="mt-2"><Link href="/subprocessors" className="text-indigo-400 hover:text-indigo-300">View our subprocessors list →</Link></p>

            <h3 className="text-xl font-semibold mt-6 mb-3">B) Business transfers</h3>
            <p className="text-gray-300">If we undergo a merger, acquisition, reorganization, or sale of assets, information may be transferred as part of that transaction.</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">C) Legal and safety</h3>
            <p className="text-gray-300 mb-2">We may disclose information when we believe it is necessary to:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Comply with law or legal process</li>
              <li>Protect rights, safety, and security of users, the Company, or the public</li>
              <li>Detect, prevent, or address fraud, abuse, or security incidents</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">6) Video Storage, Retention, and Deletion</h2>

            <h3 className="text-xl font-semibold mt-4 mb-3">A) Retention period</h3>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Uploaded videos and outputs are stored temporarily to provide the Service and enable downloads.</li>
              <li><strong>Videos and outputs are automatically deleted after 90 days.</strong></li>
            </ul>
            <p className="text-gray-400 text-sm mt-2">We may retain non-video data longer (e.g., invoices, credits ledger, security logs, analytics aggregates) as needed for legal, accounting, fraud prevention, and system integrity.</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">B) Account deletion</h3>
            <p className="text-gray-300 mb-2">We provide <strong>complete account deletion from within the app</strong>. When you delete your account:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-300">
              <li>Your account profile and identifiers will be deleted or de-identified where feasible.</li>
              <li>Certain records may be retained as required for legal, tax, dispute resolution, fraud prevention, and accounting purposes (e.g., payment records).</li>
              <li>Video retention remains subject to our deletion policies and technical constraints; we aim to delete associated stored videos/outputs consistent with the account deletion process and retention settings.</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">7) Cookies, Analytics, and Retargeting</h2>

            <h3 className="text-xl font-semibold mt-4 mb-3">A) Cookies used for essential functionality</h3>
            <p className="text-gray-300 mb-2">We use essential cookies for:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Authentication and session management</li>
              <li>Security and abuse prevention</li>
              <li>Basic site functionality</li>
            </ul>
            <p className="text-gray-400 text-sm mt-2">These cookies are necessary for the Service to work.</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">B) Analytics</h3>
            <p className="text-gray-300">We use analytics to understand usage patterns, diagnose issues, and improve the Service. Analytics may include events like signup, login, upload started, job completed, and purchase completed.</p>

            <h3 className="text-xl font-semibold mt-6 mb-3">C) Retargeting and advertising measurement</h3>
            <p className="text-gray-300 mb-2">We use retargeting tools (such as the Meta Pixel) that may:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Collect event data (e.g., page views, conversions)</li>
              <li>Help us show ads to people who have interacted with our site</li>
              <li>Measure ad performance (attribution)</li>
            </ul>
            <p className="text-gray-400 text-sm mt-2">Depending on your location, you may be able to control certain cookies via browser settings or cookie banners where required.</p>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">8) Data Security</h2>
            <p className="text-gray-300 mb-2">We implement reasonable safeguards designed to protect your information, including:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Secure connections (HTTPS)</li>
              <li>Access controls and least-privilege practices</li>
              <li>Monitoring and logging for reliability and security</li>
            </ul>
            <p className="text-gray-400 text-sm mt-3">No system can be guaranteed 100% secure. You are responsible for safeguarding your account access.</p>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">9) International Data Transfers</h2>
            <p className="text-gray-300">If you access the Service from outside the United States, your information may be processed in the U.S. or other locations where our service providers operate. Where required, we use appropriate safeguards for cross-border transfers.</p>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">10) Your Rights and Choices</h2>
            <p className="text-gray-300 mb-3">Depending on your location, you may have rights to:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300">
              <li>Access, correct, or delete personal information</li>
              <li>Object to or restrict certain processing</li>
              <li>Receive a portable copy of your data</li>
            </ul>
            <p className="text-gray-300 mt-4">
              <strong>You can delete your account inside the app.</strong> You can also contact us:
            </p>
            <ul className="list-disc pl-6 space-y-1 text-gray-300 mt-2">
              <li><a href="mailto:privacy@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">privacy@blanklogo.app</a> (requests, privacy questions)</li>
              <li><a href="mailto:support@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">support@blanklogo.app</a> (support requests)</li>
            </ul>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">11) Children&apos;s Privacy</h2>
            <p className="text-gray-300">The Service is not intended for children under 13 (or under 16 where required). We do not knowingly collect personal information from children.</p>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">12) Changes to this Policy</h2>
            <p className="text-gray-300">We may update this Privacy Policy. If changes are material, we will provide notice by updating the date above and/or providing additional notice in the Service.</p>
          </section>

          <hr className="border-gray-700" />

          <section>
            <h2 className="text-2xl font-bold mb-4">13) Contact</h2>
            <div className="bg-gray-800/50 rounded-lg p-6">
              <p className="text-white font-semibold text-lg mb-2">Dupree Ops LLC</p>
              <p className="text-gray-300">
                3425 Delaney Drive, Florida, United States<br /><br />
                <strong>Privacy:</strong> <a href="mailto:privacy@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">privacy@blanklogo.app</a><br />
                <strong>Support:</strong> <a href="mailto:support@blanklogo.app" className="text-indigo-400 hover:text-indigo-300">support@blanklogo.app</a>
              </p>
            </div>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-800">
          <div className="flex flex-wrap gap-4 text-sm text-gray-400">
            <Link href="/terms" className="hover:text-white transition">Terms of Service</Link>
            <Link href="/privacy" className="hover:text-white transition">Privacy Policy</Link>
            <Link href="/subprocessors" className="hover:text-white transition">Subprocessors</Link>
            <Link href="/" className="hover:text-white transition">Home</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
